language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=2.0
install:
  - pip install Django==$DJANGO_VERSION
  - pip install requests
  - pip install Pillow
script: python setup.py test

# Django 2.0+ supports only Python 3.x.
matrix:
    exclude:
    - python: "2.6"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "3.6"
      env: DJANGO_VERSION=1.4
    - python: "3.6"
      env: DJANGO_VERSION=1.5
    - python: "3.6"
      env: DJANGO_VERSION=1.10
    - python: "3.7"
      env: DJANGO_VERSION=1.4
    - python: "3.7"
      env: DJANGO_VERSION=1.5
    - python: "3.7"
      env: DJANGO_VERSION=1.10
      